"""Chinese localization dictionaries for NLE game messages and entities."""

MONSTER_NAMES = {
    "newt": "蝾螈", "jackal": "豺狼", "fox": "狐狸", "kobold": "狗头人",
    "goblin": "哥布林", "grid bug": "格子虫", "bat": "蝙蝠",
    "gnome": "侏儒", "dwarf": "矮人", "orc": "兽人",
    "kitten": "小猫", "little dog": "小狗", "pony": "小马",
    "housecat": "家猫", "dog": "狗", "horse": "马",
    "large cat": "大猫", "large dog": "大狗", "warhorse": "战马",
    "sewer rat": "下水道老鼠", "giant rat": "巨鼠",
    "giant ant": "巨蚁", "killer bee": "杀人蜂",
    "acid blob": "酸液粘液怪", "floating eye": "漂浮之眼",
    "yellow light": "黄光", "gas spore": "孢子怪",
    "lichen": "地衣", "brown mold": "褐霉", "green mold": "绿霉",
    "red mold": "红霉", "yellow mold": "黄霉",
    "gnome lord": "侏儒领主", "gnome king": "侏儒国王",
    "orc shaman": "兽人萨满", "hill orc": "丘陵兽人",
    "Mordor orc": "魔多兽人", "Uruk-hai": "强兽人",
    "ogre": "食人魔", "troll": "巨魔", "dragon": "龙",
    "minotaur": "牛头人", "elf": "精灵", "vampire": "吸血鬼",
    "zombie": "僵尸", "skeleton": "骷髅", "wraith": "幽灵",
    "ghost": "鬼魂", "lich": "巫妖", "demon": "恶魔",
    "shopkeeper": "店主", "guard": "卫兵",
    "human": "人类", "monk": "武僧", "valkyrie": "女武神",
    "wizard": "法师", "ranger": "游侠", "priestess": "女祭司",
    "priest": "祭司", "rogue": "盗贼", "samurai": "武士",
    "tourist": "游客", "caveman": "穴居人", "cavewoman": "穴居人",
    "barbarian": "野蛮人", "healer": "治疗师",
    "knight": "骑士", "archeologist": "考古学家",
    "rat": "老鼠", "snake": "蛇", "spider": "蛛蛛",
    "wolf": "狼", "worm": "虫", "scorpion": "蝎子",
    "centipede": "蚓蚓", "gecko": "壁虎", "iguana": "鬣蜑",
    "lizard": "蜥蜴", "crocodile": "鰄鱼",
    "rothe": "洛斯兽", "mumak": "大象",
    "jabberwock": "炸脓兽", "couatl": "羽蛇神",
    "imp": "小鬼", "homunculus": "人造人",
    "nymph": "山林仙女", "leprechaun": "小精灵",
}

ITEM_NAMES = {
    "dagger": "匕首", "short sword": "短剑", "long sword": "长剑",
    "two-handed sword": "双手剑", "mace": "钉锤", "quarterstaff": "长棍",
    "war hammer": "战锤", "spear": "长矛", "javelin": "标枪",
    "axe": "斧头", "battle-axe": "战斧", "bow": "弓", "arrow": "箭",
    "elven dagger": "精灵匕首", "orcish dagger": "兽人匕首",
    "leather armor": "皮甲", "studded leather armor": "镶钉皮甲",
    "ring mail": "环甲", "scale mail": "鳞甲", "chain mail": "锁子甲",
    "splint mail": "板条甲", "plate mail": "板甲",
    "shield": "盾牌", "cloak": "斗篷", "helm": "头盔",
    "leather gloves": "皮手套", "gauntlets": "护手", "boots": "靴子",
    "potion of healing": "治疗药水", "potion of extra healing": "高级治疗药水",
    "potion of speed": "速度药水", "potion of gain energy": "能量药水",
    "scroll of identify": "鉴定卷轴", "scroll of teleportation": "传送卷轴",
    "scroll of enchant weapon": "附魔武器卷轴",
    "scroll of enchant armor": "附魔护甲卷轴",
    "scroll of scare monster": "吓退怪物卷轴",
    "food ration": "口粮", "apple": "苹果", "orange": "橙子",
    "fortune cookie": "幸运饼干", "corpse": "尸体",
    "wand of cold": "寒冰魔杖", "wand of fire": "火焰魔杖",
    "wand of lightning": "闪电魔杖",
    "ring of shock resistance": "电击抗性戒指",
    "ring of polymorph control": "变形控制戒指",
    "cloak of magic resistance": "魔法抗性斗篷",
    "robe": "长袍", "spellbook": "魔法书",
    "magic marker": "魔法标记",
    "pair of leather gloves": "皮手套",
    "long sword": "长剑", "lance": "长枪",
    "ring mail": "环甲", "helmet": "头盔",
    "small shield": "小盾牌",
    "apple": "苹果", "carrot": "胡萝卜",
    "orange": "橙子",
    "robe": "长袍",
    "uncursed": "未诅咒的",
    "blessed": "祝福的",
    "cursed": "被诅咒的",
}

TERRAIN_NAMES = {
    "floor": "地板", "corridor": "走廊", "lit corridor": "明亮的走廊",
    "staircase up": "上楼梯", "staircase down": "下楼梯",
    "open door": "开着的门", "closed door": "关着的门",
    "wall": "墙壁", "vertical wall": "竖墙", "horizontal wall": "横墙",
    "top-left corner": "左上角墙", "top-right corner": "右上角墙",
    "bottom-left corner": "左下角墙", "bottom-right corner": "右下角墙",
    "cross wall": "十字墙",
    "upward T-wall": "T型墙", "downward T-wall": "T型墙",
    "leftward T-wall": "T型墙", "rightward T-wall": "T型墙",
    "fountain": "喷泉", "altar": "祭坛", "grave": "坟墓", "throne": "王座",
    "sink": "水槽", "pool": "水池", "lava": "岩浆", "ice": "冰面",
    "tree": "树", "iron bars": "铁栏", "dark area": "暗区", "stone": "石头",
    "ladder up": "上梯子", "ladder down": "下梯子",
    "lowered drawbridge": "放下的吁桥", "raised drawbridge": "拉起的吁桥",
}

MESSAGE_PATTERNS = [
    ("You hit", "你击中了"), ("You miss", "你没有击中"),
    ("You kill", "你杀死了"), ("You die", "你死了"),
    ("You feel", "你感觉"), ("You see", "你看到"),
    ("You hear", "你听到"), ("You find", "你发现了"),
    ("You pick up", "你捡起了"), ("You drop", "你丢弃了"),
    ("You eat", "你吃了"), ("You drink", "你喝了"),
    ("You read", "你阅读了"), ("You wear", "你穿上了"),
    ("You wield", "你装备了"), ("You begin", "你开始"),
    ("It hits", "它击中了"), ("It misses", "它没有击中"),
    ("There is", "这里有"), ("Nothing happens", "什么都没发生"),
    ("The door opens", "门打开了"), ("The door closes", "门关上了"),
    ("The door is locked", "门是锁着的"), ("Welcome to", "欢迎来到"),
    ("Goodbye", "再见"), ("Really quit", "真的要退出吗"),
    ("Not Hungry", "不饿"), ("Hungry", "饥饿"),
    ("Weak", "虚弱"), ("Fainting", "晕厥"),
    ("Salutations", "问候"), ("Hello", "你好"), ("Aloha", "你好"), ("welcome to NetHack", "欢迎来到NetHack"),
    ("You are a", "你是一个"),
    ("You swap places with", "你与...交换了位置"),
    ("You displaced", "你挪开了"),
    ("You destroy", "你摧毁了"),
    ("It bites", "它咬了"), ("It stings", "它蟀了"),
    ("attacks", "攻击了"), ("is killed", "被杀死了"),
    ("You open", "你打开了"), ("You close", "你关上了"),
    ("You climb", "你爬上了"), ("You descend", "你下降了"),
    ("The door", "门"), ("The stairway", "楼梯"),
    ("This door is locked", "这扇门是锁着的"),
    ("There are", "这里有"),
    ("neutral", "中立"), ("lawful", "守序"), ("chaotic", "混沌"),
    ("female", "女性"), ("male", "男性"),
    ("gnomish", "侏儒族"), ("human", "人类"),
    ("elven", "精灵族"), ("dwarven", "矮人族"), ("orcish", "兽人族"),
    ("Monk", "武僧"), ("Valkyrie", "女武神"),
    ("Wizard", "法师"), ("Ranger", "游侠"),
    ("Priestess", "女祭司"), ("Priest", "祭司"),
    ("Rogue", "盗贼"), ("Samurai", "武士"),
    ("Tourist", "游客"), ("Caveman", "穴居人"),
    ("Cavewoman", "穴居人"), ("Barbarian", "野蛮人"),
    ("Healer", "治疗师"), ("Knight", "骑士"),
    ("Archeologist", "考古学家"),
    ("It's solid stone.", "这是坚固的石头。"),
    ("It's a wall.", "这是一堵墙。"),
    ("solid stone", "坚固的石头"),
    ("bubbling water", "冒泡的水"),
    ("someone counting money", "有人在数钱"),
    ("a gurgling noise", "汩汩声"),
    ("the splashing of a naiad", "水仙的泵水声"),
    ("a door open", "一扇门打开"),
    ("a door close", "一扇门关闭"),
    ("a shrill humming sound", "尖锐的嗡嗡声"),
    ("crashing rock", "崩裂的岩石"),
    ("someone digging", "有人在挖掘"),
    (" your ", " 你的 "),
    ("your ", "你的"),
    ("You stop.", "你停下了。"),
    ("You start", "你开始"),
    ("You finish", "你完成了"),
    ("You can't move", "你无法移动"),
    ("You search", "你搜索"),
    ("You don't", "你没有"),
    ("You are hit", "你被击中了"),
    ("You are almost hit", "你差点被击中"),
    ("You wait.", "你等待。"),
    ("You try", "你尝试"),
    ("You step", "你踩到"),
    ("You move", "你移动"),
    ("You stumble", "你绊倒了"),
    ("You fall", "你摔倒了"),
    ("You fly", "你飞了"),
    ("You land", "你着陆了"),
    ("The kitten", "小猫"),
    ("The little dog", "小狗"),
    ("The pony", "小马"),
    ("the kitten", "小猫"),
    ("the little dog", "小狗"),
    ("the pony", "小马"),
    ("a kitten", "一只小猫"),
    ("a little dog", "一只小狗"),
    ("a pony", "一匹小马"),
    ("Satiated", "饱腹"),
    ("Hungry", "饥饿"),
    ("Adventurer", "冒险者"),
    ("Stripling", "新手"),
    ("Rambler", "漫游者"),
    ("Dungeoneer", "地牢探索者"),
    ("What do you want to eat?", "你想吃什么？"),
    ("What do you want to drink?", "你想喝什么？"),
    ("What do you want to read?", "你想阅读什么？"),
    ("What do you want to wear?", "你想穿什么？"),
    ("What do you want to wield?", "你想装备什么？"),
    ("What do you want to drop?", "你想丢弃什么？"),
    ("What do you want to throw?", "你想投掷什么？"),
    ("What do you want to use?", "你想使用什么？"),
    ("What do you want to zap?", "你想释放什么？"),
    ("You cannot eat that!", "你不能吃那个！"),
    ("You can't", "你不能"),
    ("That is not", "那不是"),
    ("You don't have", "你没有"),
    ("Nothing to eat", "没有可吃的"),
    ("You have nothing", "你什么都没有"),
    ("In what direction", "向哪个方向"),
    ("Never mind.", "算了。"),
    ("gold pieces", "金币"),
    ("gold piece", "金币"),
    ("being worn", "已穿戴"),
    ("weapon in hand", "手持武器"),
    ("alternate weapon", "副武器"),
    ("not wielded", "未装备"),
    ("in use", "使用中"),
    ("uncursed", "未诅咒"),
    ("blessed", "祝福"),
    ("cursed", "诅咒"),
    ("potion of healing", "治疗药水"),
    ("potions of healing", "治疗药水"),
    ("scroll of identify", "鉴定卷轴"),
    ("spellbook of sleep", "睡眠术魔法书"),
    ("food ration", "口粮"),
    ("food rations", "口粮"),
    ("pair of leather gloves", "皮手套"),
    ("robe", "长袍"),
    ("orange", "橙子"),
    ("oranges", "橙子"),
    ("apple", "苹果"),
    ("apples", "苹果"),
    ("carrot", "胡萝卜"),
    ("carrots", "胡萝卜"),
    ("fortune cookie", "幸运饼干"),
    ("fortune cookies", "幸运饼干"),
    ("long sword", "长剑"),
    ("short sword", "短剑"),
    ("dagger", "匹首"),
    ("lance", "长枪"),
    ("battle-axe", "战斧"),
    ("ring mail", "环甲"),
    ("helmet", "头盔"),
    ("small shield", "小盾牌"),
    ("leather armor", "皮甲"),
    ("oil lamp", "油灯"),
]

STATUS_LABELS = {
    "HP": "生命", "MP": "法力", "AC": "护甲", "Lv": "等级",
    "XP": "经验", "Gold": "金币", "St": "力量", "Dx": "敏捷",
    "Co": "体质", "In": "智力", "Wi": "感知", "Ch": "魅力",
    "Hunger": "饥饿度", "Align": "阵营", "Score": "分数",
    "Chaotic": "混乱", "Neutral": "中立", "Lawful": "守序",
}
